"""empty message

Revision ID: f33494c05d42
Revises: 1a9ea33b12b8
Create Date: 2019-11-11 22:05:07.304739

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f33494c05d42'
down_revision = '1a9ea33b12b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Venue', 'seeking_description',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('Venue', 'seeking_talent',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Venue', 'seeking_talent',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('Venue', 'seeking_description',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
